"""migration

Revision ID: 08b8f61e7f95
Revises: 4ddb4501c627
Create Date: 2023-02-09 14:32:32.853816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b8f61e7f95'
down_revision = '4ddb4501c627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
