"""migration

Revision ID: 9f652dd5390c
Revises: 
Create Date: 2023-02-05 15:07:03.928969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f652dd5390c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.Column('artist_race_primary', sa.String(), nullable=True),
    sa.Column('artist_race_secondary', sa.String(), nullable=True),
    sa.Column('racial_category', sa.String(), nullable=True),
    sa.Column('artist_bio', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('artist_dob', sa.String(), nullable=True),
    sa.Column('artist_dod', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artworks',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.Column('artist_race_primary', sa.String(), nullable=True),
    sa.Column('racial_category', sa.String(), nullable=True),
    sa.Column('artist_bio', sa.String(), nullable=True),
    sa.Column('museum_name', sa.String(), nullable=True),
    sa.Column('artwork_name', sa.String(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('date_created', sa.String(), nullable=True),
    sa.Column('formatted_date', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artworks')
    op.drop_table('artists')
    # ### end Alembic commands ###
