"""New Migration

Revision ID: b162c998fe08
Revises: fe8581c8a50c
Create Date: 2023-02-04 12:12:50.927496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b162c998fe08'
down_revision = 'fe8581c8a50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
