"""New Migration

Revision ID: c5f24ab9febb
Revises: df0e3bf2090e
Create Date: 2023-02-04 17:18:29.029886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f24ab9febb'
down_revision = 'df0e3bf2090e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
