"""migration

Revision ID: d4850267ead0
Revises: 9f652dd5390c
Create Date: 2023-02-09 05:41:54.321936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4850267ead0'
down_revision = '9f652dd5390c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
