"""New Migration

Revision ID: df0e3bf2090e
Revises: b162c998fe08
Create Date: 2023-02-04 17:08:52.743199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0e3bf2090e'
down_revision = 'b162c998fe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
